

export const RecentActivityHeaders = [
    'Date',
    'Description',
    'Type',
    'Amount',
    'Status'
]
export const transctionData = [
    {
        'date':'2024-06-01', 
        'description':'Deposit', 
        'type':'Credit', 
        'amount':'+$500.00',
        'availableBalance': '$12,450.75',
        'Currency':'USD',
        'sender':'John Doe', 
        'paymentMethod':'Bank Transfer',
        'id':'26BUN9358B802N34VNMV6',
        'status':'Completed',
    },
    {
        'date':'2024-05-25', 
        'description':'Payment Received', 
        'type':'Credit', 
        'amount':'+₦1,446,750.00',
        'availableBalance': '$13,450.75',
        'Currency':'NGN',
        'sender':'Acme Corp', 
        'receiver':'My Account',
        'paymentMethod':'PayPal',    
        'id':'VU16835BI9344128NMV6',
        'status':'Completed',
    },
    {
        'date':'2024-05-20', 
        'description':'Transfer', 
        'type':'Debit', 
        'amount':'-$150.00',
        'availableBalance': '$13,300.75',
        'account':'**** **** **** 1234',
        'Currency':'USD', 
        'receiver':'Jane Smith', 
        'paymentMethod':'Venmo',
        'id':'VYW658230M653B72NMV6',
        'status':'Pending',
    },
    {
        'date':'2024-05-15', 
        'description':'Grocery Store', 
        'type':'Credit', 
        'amount':'-₦1,085,062.50', 
        'availableBalance': '$12,550.75',
        'Currency':'NGN', 
        'receiver':'SuperMart',
        'paymentMethod':'Credit Card',
        'id':'XWZ658230M653B72NMV6',
        'status':'Completed',
    },
    {
        'date':'2024-05-10', 
        'description':'Salary', 
        'type':'Credit', 
        'amount':'+$3,000.00',
        'availableBalance': '$15,550.75',
        'Currency':'USD',
        'sender':'Tech Solutions', 
        'receiver':'My Account',
        'paymentMethod':'Direct Deposit',
        'id':'YZA658230M653B72NMV6',
        'status':'Completed',
    },
    {
        'date':'2024-05-05', 
        'description':'Electricity Bill', 
        'type':'Debit', 
        'amount':'-$120.00', 
        'availableBalance': '$15,430.75',
        'Currency':'USD',
        'sender':'My Account', 
        'receiver':'PowerGrid',
        'paymentMethod':'Auto Debit',
        'id':'KEY658230M653B72NMV6',
        'status':'Completed',
    },
    {
        'date':'2024-05-01', 
        'description':'Internet Bill', 
        'type':'Debit', 
        'amount':'-$60.00', 
        'availableBalance': '$15,370.75',
        'Currency':'USD',
        'sender':'My Account', 
        'receiver':'NetConnect',
        'paymentMethod':'Auto Debit',
        'id':'LMN658230M653B72NMV6',
        'status':'Completed',
    },
    {
        'date':'2024-04-28', 
        'description':'Transfer', 
        'type':'Debit',
        'amount':'-$200.00', 
        'availableBalance': '$15,170.75',
        'account':'**** **** **** 5678',
        'Currency':'USD', 
        'receiver':'Mike Johnson', 
        'paymentMethod':'Zelle',
        'id':'OPQ658230M653B72NMV6',
        'status':'Failed',
    }
]

/*type ARH*/


export const TransferHeaders = [
    'Date',
    'Recipient',
    'Account',
    'Amount',
    'Status'
]